# -*- coding: utf-8 -*-
"""Untitled264.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Gqfi4ysr_VcHRqmAMZRGHtmcUhSLZqIq
"""

!pip -q install numpy scipy matplotlib

import csv
import warnings
from dataclasses import dataclass, asdict
from pathlib import Path

import numpy as np
import matplotlib.pyplot as plt
from scipy.integrate import solve_bvp
from scipy.fft import dct
from google.colab import files

warnings.simplefilter("ignore", category=RuntimeWarning)

# ==========================================
# Configuration
# ==========================================

OUTPUT_DIR = Path("outputs")
OUTPUT_DIR.mkdir(exist_ok=True, parents=True)

DELTAS = [0.20, 0.10, 0.05, 0.025]
ALPHA = 10.0
BETA = 10.0

N_DST = 8192          # safer first run in Colab
N_CHEB = 2048
KMAX_SINE = 5000
MAX_NODES = 120000
TOL_BVP = 1e-4
EPS_LIST = [1e-2, 1e-3]
BATCH_SIZE = 256

# smoothing width for the step profile in numerics
# small enough to mimic the abrupt junction, large enough for stable solve_bvp
STEP_SMOOTH_FACTOR = 0.08


@dataclass
class ExperimentResult:
    delta: float
    inv_delta: float
    max_abs_uprime: float
    clip: int
    N_dst: int
    N_cheb: int
    K_H1_1e2: int
    K_H1_1e3: int
    K_L2_1e2: int
    K_L2_1e3: int
    K_cheb_1e2: int
    K_cheb_1e3: int


# ==========================================
# Model helpers
# ==========================================

def bulk_states(alpha, beta):
    u_p = np.arcsinh(-alpha / 2.0)
    u_n = np.arcsinh(beta / 2.0)
    return float(u_p), float(u_n)


def smooth_doping_step(s, alpha, beta, eta):
    """
    Smooth approximation of
        C(s) = -alpha for s<0
             =  beta  for s>0

    Formula:
        C_eta(s) = (beta-alpha)/2 + (alpha+beta)/2 * tanh(s/eta)
    """
    return 0.5 * (beta - alpha) + 0.5 * (alpha + beta) * np.tanh(s / eta)


# ==========================================
# BVP solver
# ==========================================

def solve_equilibrium_bvp(delta, alpha, beta, tol=TOL_BVP, max_nodes=MAX_NODES):
    """
    Solve
        -delta^2 u'' = exp(-u) - exp(u) + C_eta(s),  s in (-1,1)
        u(-1)=u_p, u(1)=u_n

    using a smoothed step profile C_eta(s).
    """
    u_p, u_n = bulk_states(alpha, beta)

    # narrow but not too narrow smoothing for stability
    eta = max(STEP_SMOOTH_FACTOR * delta, 0.005)

    def ode(s, y):
        u = y[0]
        up = y[1]
        C = smooth_doping_step(s, alpha, beta, eta)
        upp = (np.exp(u) - np.exp(-u) - C) / (delta ** 2)
        return np.vstack((up, upp))

    def bc(ya, yb):
        return np.array([ya[0] - u_p, yb[0] - u_n])

    # denser grid near zero
    s_left = np.linspace(-1.0, -0.15, 250, endpoint=False)
    s_mid = np.linspace(-0.15, 0.15, 500, endpoint=False)
    s_right = np.linspace(0.15, 1.0, 250)
    s_mesh = np.unique(np.concatenate([s_left, s_mid, s_right]))

    width = max(2.5 * delta, 0.03)
    u_guess = 0.5 * (u_p + u_n) + 0.5 * (u_n - u_p) * np.tanh(s_mesh / width)
    up_guess = 0.5 * (u_n - u_p) * (1.0 / width) * (1.0 / np.cosh(s_mesh / width) ** 2)
    y_guess = np.vstack((u_guess, up_guess))

    sol = solve_bvp(
        ode,
        bc,
        s_mesh,
        y_guess,
        tol=tol,
        max_nodes=max_nodes,
        verbose=0
    )

    if not sol.success:
        raise RuntimeError(
            f"BVP solver failed for delta={delta}: status={sol.status}, message={sol.message}"
        )

    return sol, eta


# ==========================================
# Residual construction
# ==========================================

def evaluate_solution_and_residual(sol, n_points=N_DST):
    s = np.linspace(-1.0, 1.0, n_points)
    vals = sol.sol(s)
    u = vals[0]
    up = vals[1]

    a = 0.5 * (u[-1] + u[0])
    b = 0.5 * (u[-1] - u[0])
    u_lin = a + b * s
    w = u - u_lin
    wp = up - b

    return {
        "s": s,
        "u": u,
        "up": up,
        "u_lin": u_lin,
        "w": w,
        "wp": wp,
        "a": a,
        "b": b,
    }


# ==========================================
# Spectral coefficients
# ==========================================

def compute_sine_coeffs(w, s, kmax=KMAX_SINE, batch_size=BATCH_SIZE):
    coeffs = np.zeros(kmax, dtype=float)
    x = s[None, :]

    for start in range(1, kmax + 1, batch_size):
        stop = min(start + batch_size - 1, kmax)
        ks = np.arange(start, stop + 1)[:, None]
        basis = np.sin(ks * np.pi * (x + 1.0) / 2.0)
        coeffs[start - 1:stop] = np.trapz(basis * w[None, :], s, axis=1)

    return coeffs


def chebyshev_lobatto_nodes(n):
    j = np.arange(n)
    x_desc = np.cos(np.pi * j / (n - 1))
    return x_desc[::-1]


def chebyshev_coefficients_from_values_on_lobatto(values_ascending):
    f = values_ascending[::-1]
    n = len(f)
    c = dct(f, type=1) / (n - 1)
    c[0] *= 0.5
    c[-1] *= 0.5
    return c


# ==========================================
# Resolution indices
# ==========================================

def tail_from_coeffs_l2(coeffs):
    sq = coeffs ** 2
    rev_cumsum = np.cumsum(sq[::-1])[::-1]
    tail = np.empty_like(rev_cumsum)
    tail[:-1] = rev_cumsum[1:]
    tail[-1] = 0.0
    return tail


def tail_from_coeffs_h1_sine(coeffs):
    k = np.arange(1, len(coeffs) + 1, dtype=float)
    weights = (k * np.pi / 2.0) ** 2
    sq = weights * (coeffs ** 2)
    rev_cumsum = np.cumsum(sq[::-1])[::-1]
    tail = np.empty_like(rev_cumsum)
    tail[:-1] = rev_cumsum[1:]
    tail[-1] = 0.0
    return tail


def find_resolution_index(tail, total_energy, eps):
    threshold = (eps ** 2) * total_energy
    idx = np.where(tail <= threshold)[0]
    if len(idx) == 0:
        raise ValueError(
            f"Resolution index not found for eps={eps}. Increase KMAX_SINE or N_CHEB."
        )
    return int(idx[0] + 1)


def compute_indices_from_sine_coeffs(coeffs, wp, s):
    total_h1 = float(np.trapz(wp ** 2, s))
    if total_h1 <= 0:
        raise ValueError("Nonpositive H1 energy encountered.")

    h1_tail = tail_from_coeffs_h1_sine(coeffs)

    total_l2 = float(np.sum(coeffs ** 2))
    if total_l2 <= 0:
        raise ValueError("Nonpositive L2 coefficient energy encountered.")

    l2_tail = tail_from_coeffs_l2(coeffs)

    out = {}
    for eps in EPS_LIST:
        tag = "1e2" if abs(eps - 1e-2) < 1e-15 else "1e3"
        out[f"K_H1_{tag}"] = find_resolution_index(h1_tail, total_h1, eps)
        out[f"K_L2_{tag}"] = find_resolution_index(l2_tail, total_l2, eps)
    return out


def compute_indices_from_cheb_coeffs(coeffs):
    sq = coeffs ** 2
    total = float(np.sum(sq))
    if total <= 0:
        raise ValueError("Nonpositive Chebyshev coefficient energy encountered.")

    rev_cumsum = np.cumsum(sq[::-1])[::-1]
    tail = np.empty_like(rev_cumsum)
    tail[:-1] = rev_cumsum[1:]
    tail[-1] = 0.0

    out = {}
    for eps in EPS_LIST:
        tag = "1e2" if abs(eps - 1e-2) < 1e-15 else "1e3"
        out[f"K_cheb_{tag}"] = find_resolution_index(tail, total, eps)
    return out


# ==========================================
# Plotting
# ==========================================

def make_profile_plot(curves, outpath):
    plt.figure(figsize=(7.5, 4.8))
    for item in curves:
        plt.plot(item["s"], item["u"], label=fr"$\delta={item['delta']}$")
    plt.xlabel(r"$s$")
    plt.ylabel(r"$u(s)$")
    plt.title("Equilibrium Poisson--Boltzmann profiles")
    plt.legend()
    plt.tight_layout()
    plt.savefig(outpath, dpi=300, bbox_inches="tight")
    plt.close()


def make_residual_derivative_plot(curves, outpath):
    plt.figure(figsize=(7.5, 4.8))
    for item in curves:
        plt.plot(item["s"], item["wp"], label=fr"$\delta={item['delta']}$")
    plt.xlabel(r"$s$")
    plt.ylabel(r"$w_\delta'(s)$")
    plt.title("Derivative of the residual profile")
    plt.legend()
    plt.tight_layout()
    plt.savefig(outpath, dpi=300, bbox_inches="tight")
    plt.close()


def make_scaling_plot(results, outpath):
    inv_delta = np.array([r.inv_delta for r in results], dtype=float)
    kh1 = np.array([r.K_H1_1e2 for r in results], dtype=float)
    kl2 = np.array([r.K_L2_1e2 for r in results], dtype=float)
    kcheb = np.array([r.K_cheb_1e2 for r in results], dtype=float)

    plt.figure(figsize=(7.5, 4.8))
    plt.plot(inv_delta, kh1, marker="o", label=r"$K_{H^1}(10^{-2})$")
    plt.plot(inv_delta, kl2, marker="s", label=r"$K_{L^2}(10^{-2})$")
    plt.plot(inv_delta, kcheb, marker="^", label=r"$K_{\mathrm{cheb}}(10^{-2})$")
    plt.xlabel(r"$1/\delta = L/L_D$")
    plt.ylabel("Effective spectral dimension")
    plt.title("Observed dependence of effective dimension on reciprocal Debye scale")
    plt.legend()
    plt.tight_layout()
    plt.savefig(outpath, dpi=300, bbox_inches="tight")
    plt.close()


# ==========================================
# Export helpers
# ==========================================

def write_results_csv(results, outpath):
    fieldnames = list(asdict(results[0]).keys())
    with open(outpath, "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        for r in results:
            writer.writerow(asdict(r))


def make_latex_table(results):
    lines = []
    lines.append(r"\begin{table}[htbp]")
    lines.append(r"\centering")
    lines.append(
        r"\caption{Numerical resolution diagnostics for the finite-interval equilibrium problem as "
        r"\(\delta=L_D/L\) decreases. The primary theorem-aligned quantity is the energy-based sine "
        r"index \(K_\varepsilon^{H^1,\sin}\) defined in \eqref{eq:Keps_sine_H1}. For comparison, we also "
        r"report the supplementary unweighted sine indices \(K_\varepsilon^{L^2,\sin}\) from "
        r"\eqref{eq:Keps_sine_L2} and the corresponding Chebyshev-based indices. These data are included "
        r"only as numerical illustrations of the same layer-driven reciprocal-Debye trend; they do not "
        r"constitute a verification of the lower-bound theorem.}"
    )
    lines.append(r"\label{tab:scaling_results}")
    lines.append("")
    lines.append(r"\scriptsize")
    lines.append(r"\setlength{\tabcolsep}{2.8pt}")
    lines.append("")
    lines.append(r"\begin{tabular}{cccccccccccc}")
    lines.append(r"\toprule")
    lines.append(
        r"\(\delta\) & \(1/\delta\) & \(\max |u'|\) & clip & "
        r"\(N_{\mathrm{dst}}\) & \(N_{\mathrm{cheb}}\) & "
        r"\(K_{H^1}(10^{-2})\) & \(K_{H^1}(10^{-3})\) & "
        r"\(K_{L^2}(10^{-2})\) & \(K_{L^2}(10^{-3})\) & "
        r"\(K_{\mathrm{cheb}}(10^{-2})\) & \(K_{\mathrm{cheb}}(10^{-3})\) \\"
    )
    lines.append(r"\midrule")

    for r in results:
        delta_str = f"{r.delta:.3f}".rstrip("0").rstrip(".")
        inv_delta_str = f"{int(round(r.inv_delta))}"
        row = (
            f"{delta_str} & {inv_delta_str} & {r.max_abs_uprime:.1f} & {r.clip} & "
            f"{r.N_dst} & {r.N_cheb} & "
            f"\\textbf{{{r.K_H1_1e2}}} & \\textbf{{{r.K_H1_1e3}}} & "
            f"{r.K_L2_1e2} & {r.K_L2_1e3} & "
            f"{r.K_cheb_1e2} & {r.K_cheb_1e3} \\\\"
        )
        lines.append(row)

    lines.append(r"\bottomrule")
    lines.append(r"\end{tabular}")
    lines.append(r"\end{table}")
    return "\n".join(lines)


# ==========================================
# Main run
# ==========================================

results = []
curves = []

for delta in DELTAS:
    print(f"[INFO] Solving delta = {delta}")
    sol, eta = solve_equilibrium_bvp(delta, ALPHA, BETA)

    sampled = evaluate_solution_and_residual(sol, n_points=N_DST)
    s = sampled["s"]
    u = sampled["u"]
    up = sampled["up"]
    w = sampled["w"]
    wp = sampled["wp"]

    print(f"[INFO] Computing sine coefficients for delta = {delta}")
    coeffs_sine = compute_sine_coeffs(w, s, kmax=KMAX_SINE)

    sine_idx = compute_indices_from_sine_coeffs(coeffs_sine, wp, s)

    print(f"[INFO] Computing Chebyshev coefficients for delta = {delta}")
    x_cheb = chebyshev_lobatto_nodes(N_CHEB)
    u_cheb = sol.sol(x_cheb)[0]
    coeffs_cheb = chebyshev_coefficients_from_values_on_lobatto(u_cheb)
    cheb_idx = compute_indices_from_cheb_coeffs(coeffs_cheb)

    result = ExperimentResult(
        delta=delta,
        inv_delta=1.0 / delta,
        max_abs_uprime=float(np.max(np.abs(up))),
        clip=0,
        N_dst=N_DST,
        N_cheb=N_CHEB,
        K_H1_1e2=sine_idx["K_H1_1e2"],
        K_H1_1e3=sine_idx["K_H1_1e3"],
        K_L2_1e2=sine_idx["K_L2_1e2"],
        K_L2_1e3=sine_idx["K_L2_1e3"],
        K_cheb_1e2=cheb_idx["K_cheb_1e2"],
        K_cheb_1e3=cheb_idx["K_cheb_1e3"],
    )

    results.append(result)
    curves.append({
        "delta": delta,
        "s": s,
        "u": u,
        "wp": wp,
    })

results.sort(key=lambda r: r.delta, reverse=True)
curves.sort(key=lambda d: d["delta"], reverse=True)

write_results_csv(results, OUTPUT_DIR / "results.csv")
latex_table = make_latex_table(results)
with open(OUTPUT_DIR / "scaling_table.tex", "w", encoding="utf-8") as f:
    f.write(latex_table)

make_profile_plot(curves, OUTPUT_DIR / "profiles_delta.png")
make_residual_derivative_plot(curves, OUTPUT_DIR / "residual_derivative_delta.png")
make_scaling_plot(results, OUTPUT_DIR / "scaling_plot.png")

print("\n[INFO] Numerical summary")
for r in results:
    print(
        f"delta={r.delta:>6g} | "
        f"K_H1(1e-2)={r.K_H1_1e2:>5d}, "
        f"K_H1(1e-3)={r.K_H1_1e3:>5d}, "
        f"K_L2(1e-2)={r.K_L2_1e2:>5d}, "
        f"K_L2(1e-3)={r.K_L2_1e3:>5d}, "
        f"K_cheb(1e-2)={r.K_cheb_1e2:>5d}, "
        f"K_cheb(1e-3)={r.K_cheb_1e3:>5d}"
    )

print("\n[INFO] Files saved in outputs/:")
for p in [
    OUTPUT_DIR / "results.csv",
    OUTPUT_DIR / "scaling_table.tex",
    OUTPUT_DIR / "profiles_delta.png",
    OUTPUT_DIR / "residual_derivative_delta.png",
    OUTPUT_DIR / "scaling_plot.png",
]:
    print(" -", p)

files.download("outputs/results.csv")
files.download("outputs/scaling_table.tex")
files.download("outputs/profiles_delta.png")
files.download("outputs/residual_derivative_delta.png")
files.download("outputs/scaling_plot.png")