# -*- coding: utf-8 -*-
"""Untitled250.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1goYEl-jflJkrQK6_eI9gKegBk6XgKUZ6
"""

import numpy as np
import matplotlib.pyplot as plt
from scipy.optimize import root

# ============================================================
# Parameters
# ============================================================
ALPHA = 1e4
BETA = 1e4
DELTA_LIST = [0.2, 0.1, 0.05, 0.025]

if abs(ALPHA - BETA) > 1e-14:
    raise ValueError(
        "This solver is written for the symmetric case ALPHA = BETA. "
        "For asymmetric doping, a separate version is needed."
    )

# ============================================================
# Bulk states
# ============================================================
u_n = np.arcsinh(BETA / 2.0)
u_p = -u_n

def u_lin(s: np.ndarray) -> np.ndarray:
    return u_p + 0.5 * (u_n - u_p) * (s + 1.0)

def C_of_s(s: np.ndarray) -> np.ndarray:
    return np.where(s < 0.0, -ALPHA, BETA)

# ============================================================
# Nonuniform grid clustered near s = 0
# x in [-1,1], map by s = sign(x)*|x|^p with p>1
# ============================================================
def make_clustered_grid(n_points: int = 2001, power: float = 2.5) -> np.ndarray:
    x = np.linspace(-1.0, 1.0, n_points)
    s = np.sign(x) * np.abs(x) ** power
    s[0] = -1.0
    s[-1] = 1.0
    s = np.unique(s)
    return s

# ============================================================
# Nonlinear finite-difference solver
# Equation:
#   -delta^2 u'' = e^{-u} - e^u + C(s)
# BC:
#   u(-1)=u_p, u(1)=u_n
# ============================================================
def solve_profile_fd(delta: float,
                     n_points: int = 2001,
                     power: float = 2.5,
                     tol: float = 1e-10):
    s = make_clustered_grid(n_points=n_points, power=power)
    N = len(s)
    C = C_of_s(s)

    # Good initial guess:
    # local bulk profile + mild transition near 0
    u0 = np.arcsinh(C / 2.0)
    u0 += 0.15 * np.tanh(s / max(delta, 1e-3))

    def residual(u: np.ndarray) -> np.ndarray:
        r = np.zeros_like(u)

        # Boundary conditions
        r[0] = u[0] - u_p
        r[-1] = u[-1] - u_n

        # Interior nodes: second derivative on nonuniform grid
        for i in range(1, N - 1):
            h_minus = s[i] - s[i - 1]
            h_plus = s[i + 1] - s[i]

            u_xx = 2.0 * (
                (u[i + 1] - u[i]) / h_plus - (u[i] - u[i - 1]) / h_minus
            ) / (h_plus + h_minus)

            r[i] = -delta**2 * u_xx - np.exp(-u[i]) + np.exp(u[i]) - C[i]

        return r

    sol = root(
        residual,
        u0,
        method="hybr",
        options={"maxfev": 50000}
    )

    if not sol.success:
        raise RuntimeError(
            f"Finite-difference nonlinear solve failed for delta={delta}: {sol.message}"
        )

    u = sol.x

    # Compute derivative on the nonuniform grid
    up = np.gradient(u, s)

    # Residual profile
    w = u - u_lin(s)
    wp = up - 0.5 * (u_n - u_p)

    # Basic diagnostic
    res_norm = np.max(np.abs(residual(u)))
    print(
        f"delta={delta:0.5f} | success={sol.success} | "
        f"max residual={res_norm:.3e}"
    )

    return s, u, up, w, wp, res_norm

# ============================================================
# Solve all profiles
# ============================================================
profiles = {}
for delta in DELTA_LIST:
    s, u, up, w, wp, res_norm = solve_profile_fd(
        delta,
        n_points=2001,
        power=2.5
    )
    profiles[delta] = (s, u, up, w, wp, res_norm)

# ============================================================
# Figure 1: profiles u(s)
# ============================================================
plt.figure(figsize=(8, 5))
for delta in DELTA_LIST:
    s, u, up, w, wp, res_norm = profiles[delta]
    plt.plot(s, u, label=fr"$\delta={delta}$")
plt.xlabel(r"$s$")
plt.ylabel(r"$u(s)$")
plt.title(r"Equilibrium Poisson--Boltzmann profiles for decreasing $\delta$")
plt.legend()
plt.tight_layout()
plt.savefig("profiles_delta.png", dpi=300)
plt.close()

# ============================================================
# Figure 2: residual derivative w'(s)
# ============================================================
plt.figure(figsize=(8, 5))
for delta in DELTA_LIST:
    s, u, up, w, wp, res_norm = profiles[delta]
    plt.plot(s, wp, label=fr"$\delta={delta}$")
plt.xlabel(r"$s$")
plt.ylabel(r"$w_\delta'(s)$")
plt.title(r"Concentration of the residual derivative near the internal layer")
plt.legend()
plt.tight_layout()
plt.savefig("residual_derivative_delta.png", dpi=300)
plt.close()

print("\nSaved:")
print("  - profiles_delta.png")
print("  - residual_derivative_delta.png")